// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AccountOidc struct {
	pulumi.CustomResourceState

	// The resource ID for the auth method.
	AuthMethodId pulumi.StringOutput `pulumi:"authMethodId"`
	// The account description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The OIDC issuer.
	Issuer pulumi.StringPtrOutput `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The OIDC subject.
	Subject pulumi.StringPtrOutput `pulumi:"subject"`
}

// NewAccountOidc registers a new resource with the given unique name, arguments, and options.
func NewAccountOidc(ctx *pulumi.Context,
	name string, args *AccountOidcArgs, opts ...pulumi.ResourceOption) (*AccountOidc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AuthMethodId == nil {
		return nil, errors.New("invalid value for required argument 'AuthMethodId'")
	}
	var resource AccountOidc
	err := ctx.RegisterResource("boundary:index/accountOidc:AccountOidc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccountOidc gets an existing AccountOidc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccountOidc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountOidcState, opts ...pulumi.ResourceOption) (*AccountOidc, error) {
	var resource AccountOidc
	err := ctx.ReadResource("boundary:index/accountOidc:AccountOidc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AccountOidc resources.
type accountOidcState struct {
	// The resource ID for the auth method.
	AuthMethodId *string `pulumi:"authMethodId"`
	// The account description.
	Description *string `pulumi:"description"`
	// The OIDC issuer.
	Issuer *string `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The OIDC subject.
	Subject *string `pulumi:"subject"`
}

type AccountOidcState struct {
	// The resource ID for the auth method.
	AuthMethodId pulumi.StringPtrInput
	// The account description.
	Description pulumi.StringPtrInput
	// The OIDC issuer.
	Issuer pulumi.StringPtrInput
	// The account name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The OIDC subject.
	Subject pulumi.StringPtrInput
}

func (AccountOidcState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountOidcState)(nil)).Elem()
}

type accountOidcArgs struct {
	// The resource ID for the auth method.
	AuthMethodId string `pulumi:"authMethodId"`
	// The account description.
	Description *string `pulumi:"description"`
	// The OIDC issuer.
	Issuer *string `pulumi:"issuer"`
	// The account name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The OIDC subject.
	Subject *string `pulumi:"subject"`
}

// The set of arguments for constructing a AccountOidc resource.
type AccountOidcArgs struct {
	// The resource ID for the auth method.
	AuthMethodId pulumi.StringInput
	// The account description.
	Description pulumi.StringPtrInput
	// The OIDC issuer.
	Issuer pulumi.StringPtrInput
	// The account name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The OIDC subject.
	Subject pulumi.StringPtrInput
}

func (AccountOidcArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountOidcArgs)(nil)).Elem()
}

type AccountOidcInput interface {
	pulumi.Input

	ToAccountOidcOutput() AccountOidcOutput
	ToAccountOidcOutputWithContext(ctx context.Context) AccountOidcOutput
}

func (*AccountOidc) ElementType() reflect.Type {
	return reflect.TypeOf((**AccountOidc)(nil)).Elem()
}

func (i *AccountOidc) ToAccountOidcOutput() AccountOidcOutput {
	return i.ToAccountOidcOutputWithContext(context.Background())
}

func (i *AccountOidc) ToAccountOidcOutputWithContext(ctx context.Context) AccountOidcOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOidcOutput)
}

// AccountOidcArrayInput is an input type that accepts AccountOidcArray and AccountOidcArrayOutput values.
// You can construct a concrete instance of `AccountOidcArrayInput` via:
//
//          AccountOidcArray{ AccountOidcArgs{...} }
type AccountOidcArrayInput interface {
	pulumi.Input

	ToAccountOidcArrayOutput() AccountOidcArrayOutput
	ToAccountOidcArrayOutputWithContext(context.Context) AccountOidcArrayOutput
}

type AccountOidcArray []AccountOidcInput

func (AccountOidcArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AccountOidc)(nil)).Elem()
}

func (i AccountOidcArray) ToAccountOidcArrayOutput() AccountOidcArrayOutput {
	return i.ToAccountOidcArrayOutputWithContext(context.Background())
}

func (i AccountOidcArray) ToAccountOidcArrayOutputWithContext(ctx context.Context) AccountOidcArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOidcArrayOutput)
}

// AccountOidcMapInput is an input type that accepts AccountOidcMap and AccountOidcMapOutput values.
// You can construct a concrete instance of `AccountOidcMapInput` via:
//
//          AccountOidcMap{ "key": AccountOidcArgs{...} }
type AccountOidcMapInput interface {
	pulumi.Input

	ToAccountOidcMapOutput() AccountOidcMapOutput
	ToAccountOidcMapOutputWithContext(context.Context) AccountOidcMapOutput
}

type AccountOidcMap map[string]AccountOidcInput

func (AccountOidcMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AccountOidc)(nil)).Elem()
}

func (i AccountOidcMap) ToAccountOidcMapOutput() AccountOidcMapOutput {
	return i.ToAccountOidcMapOutputWithContext(context.Background())
}

func (i AccountOidcMap) ToAccountOidcMapOutputWithContext(ctx context.Context) AccountOidcMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOidcMapOutput)
}

type AccountOidcOutput struct{ *pulumi.OutputState }

func (AccountOidcOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AccountOidc)(nil)).Elem()
}

func (o AccountOidcOutput) ToAccountOidcOutput() AccountOidcOutput {
	return o
}

func (o AccountOidcOutput) ToAccountOidcOutputWithContext(ctx context.Context) AccountOidcOutput {
	return o
}

// The resource ID for the auth method.
func (o AccountOidcOutput) AuthMethodId() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountOidc) pulumi.StringOutput { return v.AuthMethodId }).(pulumi.StringOutput)
}

// The account description.
func (o AccountOidcOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AccountOidc) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The OIDC issuer.
func (o AccountOidcOutput) Issuer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AccountOidc) pulumi.StringPtrOutput { return v.Issuer }).(pulumi.StringPtrOutput)
}

// The account name. Defaults to the resource name.
func (o AccountOidcOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AccountOidc) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The OIDC subject.
func (o AccountOidcOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AccountOidc) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

type AccountOidcArrayOutput struct{ *pulumi.OutputState }

func (AccountOidcArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AccountOidc)(nil)).Elem()
}

func (o AccountOidcArrayOutput) ToAccountOidcArrayOutput() AccountOidcArrayOutput {
	return o
}

func (o AccountOidcArrayOutput) ToAccountOidcArrayOutputWithContext(ctx context.Context) AccountOidcArrayOutput {
	return o
}

func (o AccountOidcArrayOutput) Index(i pulumi.IntInput) AccountOidcOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AccountOidc {
		return vs[0].([]*AccountOidc)[vs[1].(int)]
	}).(AccountOidcOutput)
}

type AccountOidcMapOutput struct{ *pulumi.OutputState }

func (AccountOidcMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AccountOidc)(nil)).Elem()
}

func (o AccountOidcMapOutput) ToAccountOidcMapOutput() AccountOidcMapOutput {
	return o
}

func (o AccountOidcMapOutput) ToAccountOidcMapOutputWithContext(ctx context.Context) AccountOidcMapOutput {
	return o
}

func (o AccountOidcMapOutput) MapIndex(k pulumi.StringInput) AccountOidcOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AccountOidc {
		return vs[0].(map[string]*AccountOidc)[vs[1].(string)]
	}).(AccountOidcOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountOidcInput)(nil)).Elem(), &AccountOidc{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountOidcArrayInput)(nil)).Elem(), AccountOidcArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountOidcMapInput)(nil)).Elem(), AccountOidcMap{})
	pulumi.RegisterOutputType(AccountOidcOutput{})
	pulumi.RegisterOutputType(AccountOidcArrayOutput{})
	pulumi.RegisterOutputType(AccountOidcMapOutput{})
}
