// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type HostSetStatic struct {
	pulumi.CustomResourceState

	// The host set description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId pulumi.StringOutput `pulumi:"hostCatalogId"`
	// The list of host IDs contained in this set.
	HostIds pulumi.StringArrayOutput `pulumi:"hostIds"`
	// The host set name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The type of host set
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewHostSetStatic registers a new resource with the given unique name, arguments, and options.
func NewHostSetStatic(ctx *pulumi.Context,
	name string, args *HostSetStaticArgs, opts ...pulumi.ResourceOption) (*HostSetStatic, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HostCatalogId == nil {
		return nil, errors.New("invalid value for required argument 'HostCatalogId'")
	}
	var resource HostSetStatic
	err := ctx.RegisterResource("boundary:index/hostSetStatic:HostSetStatic", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHostSetStatic gets an existing HostSetStatic resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHostSetStatic(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HostSetStaticState, opts ...pulumi.ResourceOption) (*HostSetStatic, error) {
	var resource HostSetStatic
	err := ctx.ReadResource("boundary:index/hostSetStatic:HostSetStatic", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HostSetStatic resources.
type hostSetStaticState struct {
	// The host set description.
	Description *string `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId *string `pulumi:"hostCatalogId"`
	// The list of host IDs contained in this set.
	HostIds []string `pulumi:"hostIds"`
	// The host set name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The type of host set
	Type *string `pulumi:"type"`
}

type HostSetStaticState struct {
	// The host set description.
	Description pulumi.StringPtrInput
	// The catalog for the host set.
	HostCatalogId pulumi.StringPtrInput
	// The list of host IDs contained in this set.
	HostIds pulumi.StringArrayInput
	// The host set name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The type of host set
	Type pulumi.StringPtrInput
}

func (HostSetStaticState) ElementType() reflect.Type {
	return reflect.TypeOf((*hostSetStaticState)(nil)).Elem()
}

type hostSetStaticArgs struct {
	// The host set description.
	Description *string `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId string `pulumi:"hostCatalogId"`
	// The list of host IDs contained in this set.
	HostIds []string `pulumi:"hostIds"`
	// The host set name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The type of host set
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a HostSetStatic resource.
type HostSetStaticArgs struct {
	// The host set description.
	Description pulumi.StringPtrInput
	// The catalog for the host set.
	HostCatalogId pulumi.StringInput
	// The list of host IDs contained in this set.
	HostIds pulumi.StringArrayInput
	// The host set name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The type of host set
	Type pulumi.StringPtrInput
}

func (HostSetStaticArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hostSetStaticArgs)(nil)).Elem()
}

type HostSetStaticInput interface {
	pulumi.Input

	ToHostSetStaticOutput() HostSetStaticOutput
	ToHostSetStaticOutputWithContext(ctx context.Context) HostSetStaticOutput
}

func (*HostSetStatic) ElementType() reflect.Type {
	return reflect.TypeOf((**HostSetStatic)(nil)).Elem()
}

func (i *HostSetStatic) ToHostSetStaticOutput() HostSetStaticOutput {
	return i.ToHostSetStaticOutputWithContext(context.Background())
}

func (i *HostSetStatic) ToHostSetStaticOutputWithContext(ctx context.Context) HostSetStaticOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetStaticOutput)
}

// HostSetStaticArrayInput is an input type that accepts HostSetStaticArray and HostSetStaticArrayOutput values.
// You can construct a concrete instance of `HostSetStaticArrayInput` via:
//
//          HostSetStaticArray{ HostSetStaticArgs{...} }
type HostSetStaticArrayInput interface {
	pulumi.Input

	ToHostSetStaticArrayOutput() HostSetStaticArrayOutput
	ToHostSetStaticArrayOutputWithContext(context.Context) HostSetStaticArrayOutput
}

type HostSetStaticArray []HostSetStaticInput

func (HostSetStaticArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HostSetStatic)(nil)).Elem()
}

func (i HostSetStaticArray) ToHostSetStaticArrayOutput() HostSetStaticArrayOutput {
	return i.ToHostSetStaticArrayOutputWithContext(context.Background())
}

func (i HostSetStaticArray) ToHostSetStaticArrayOutputWithContext(ctx context.Context) HostSetStaticArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetStaticArrayOutput)
}

// HostSetStaticMapInput is an input type that accepts HostSetStaticMap and HostSetStaticMapOutput values.
// You can construct a concrete instance of `HostSetStaticMapInput` via:
//
//          HostSetStaticMap{ "key": HostSetStaticArgs{...} }
type HostSetStaticMapInput interface {
	pulumi.Input

	ToHostSetStaticMapOutput() HostSetStaticMapOutput
	ToHostSetStaticMapOutputWithContext(context.Context) HostSetStaticMapOutput
}

type HostSetStaticMap map[string]HostSetStaticInput

func (HostSetStaticMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HostSetStatic)(nil)).Elem()
}

func (i HostSetStaticMap) ToHostSetStaticMapOutput() HostSetStaticMapOutput {
	return i.ToHostSetStaticMapOutputWithContext(context.Background())
}

func (i HostSetStaticMap) ToHostSetStaticMapOutputWithContext(ctx context.Context) HostSetStaticMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetStaticMapOutput)
}

type HostSetStaticOutput struct{ *pulumi.OutputState }

func (HostSetStaticOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HostSetStatic)(nil)).Elem()
}

func (o HostSetStaticOutput) ToHostSetStaticOutput() HostSetStaticOutput {
	return o
}

func (o HostSetStaticOutput) ToHostSetStaticOutputWithContext(ctx context.Context) HostSetStaticOutput {
	return o
}

// The host set description.
func (o HostSetStaticOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HostSetStatic) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The catalog for the host set.
func (o HostSetStaticOutput) HostCatalogId() pulumi.StringOutput {
	return o.ApplyT(func(v *HostSetStatic) pulumi.StringOutput { return v.HostCatalogId }).(pulumi.StringOutput)
}

// The list of host IDs contained in this set.
func (o HostSetStaticOutput) HostIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HostSetStatic) pulumi.StringArrayOutput { return v.HostIds }).(pulumi.StringArrayOutput)
}

// The host set name. Defaults to the resource name.
func (o HostSetStaticOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *HostSetStatic) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The type of host set
func (o HostSetStaticOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HostSetStatic) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type HostSetStaticArrayOutput struct{ *pulumi.OutputState }

func (HostSetStaticArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HostSetStatic)(nil)).Elem()
}

func (o HostSetStaticArrayOutput) ToHostSetStaticArrayOutput() HostSetStaticArrayOutput {
	return o
}

func (o HostSetStaticArrayOutput) ToHostSetStaticArrayOutputWithContext(ctx context.Context) HostSetStaticArrayOutput {
	return o
}

func (o HostSetStaticArrayOutput) Index(i pulumi.IntInput) HostSetStaticOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HostSetStatic {
		return vs[0].([]*HostSetStatic)[vs[1].(int)]
	}).(HostSetStaticOutput)
}

type HostSetStaticMapOutput struct{ *pulumi.OutputState }

func (HostSetStaticMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HostSetStatic)(nil)).Elem()
}

func (o HostSetStaticMapOutput) ToHostSetStaticMapOutput() HostSetStaticMapOutput {
	return o
}

func (o HostSetStaticMapOutput) ToHostSetStaticMapOutputWithContext(ctx context.Context) HostSetStaticMapOutput {
	return o
}

func (o HostSetStaticMapOutput) MapIndex(k pulumi.StringInput) HostSetStaticOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HostSetStatic {
		return vs[0].(map[string]*HostSetStatic)[vs[1].(string)]
	}).(HostSetStaticOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetStaticInput)(nil)).Elem(), &HostSetStatic{})
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetStaticArrayInput)(nil)).Elem(), HostSetStaticArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetStaticMapInput)(nil)).Elem(), HostSetStaticMap{})
	pulumi.RegisterOutputType(HostSetStaticOutput{})
	pulumi.RegisterOutputType(HostSetStaticArrayOutput{})
	pulumi.RegisterOutputType(HostSetStaticMapOutput{})
}
