// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type HostSetPlugin struct {
	pulumi.CustomResourceState

	// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
	// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
	AttributesJson pulumi.StringPtrOutput `pulumi:"attributesJson"`
	// The host set description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId pulumi.StringOutput `pulumi:"hostCatalogId"`
	// The host set name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The ordered list of preferred endpoints.
	PreferredEndpoints pulumi.StringArrayOutput `pulumi:"preferredEndpoints"`
	// The value to set for the sync interval seconds.
	SyncIntervalSeconds pulumi.IntPtrOutput `pulumi:"syncIntervalSeconds"`
	// The type of host set
	Type pulumi.StringPtrOutput `pulumi:"type"`
}

// NewHostSetPlugin registers a new resource with the given unique name, arguments, and options.
func NewHostSetPlugin(ctx *pulumi.Context,
	name string, args *HostSetPluginArgs, opts ...pulumi.ResourceOption) (*HostSetPlugin, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HostCatalogId == nil {
		return nil, errors.New("invalid value for required argument 'HostCatalogId'")
	}
	var resource HostSetPlugin
	err := ctx.RegisterResource("boundary:index/hostSetPlugin:HostSetPlugin", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHostSetPlugin gets an existing HostSetPlugin resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHostSetPlugin(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HostSetPluginState, opts ...pulumi.ResourceOption) (*HostSetPlugin, error) {
	var resource HostSetPlugin
	err := ctx.ReadResource("boundary:index/hostSetPlugin:HostSetPlugin", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HostSetPlugin resources.
type hostSetPluginState struct {
	// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
	// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
	AttributesJson *string `pulumi:"attributesJson"`
	// The host set description.
	Description *string `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId *string `pulumi:"hostCatalogId"`
	// The host set name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The ordered list of preferred endpoints.
	PreferredEndpoints []string `pulumi:"preferredEndpoints"`
	// The value to set for the sync interval seconds.
	SyncIntervalSeconds *int `pulumi:"syncIntervalSeconds"`
	// The type of host set
	Type *string `pulumi:"type"`
}

type HostSetPluginState struct {
	// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
	// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
	AttributesJson pulumi.StringPtrInput
	// The host set description.
	Description pulumi.StringPtrInput
	// The catalog for the host set.
	HostCatalogId pulumi.StringPtrInput
	// The host set name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The ordered list of preferred endpoints.
	PreferredEndpoints pulumi.StringArrayInput
	// The value to set for the sync interval seconds.
	SyncIntervalSeconds pulumi.IntPtrInput
	// The type of host set
	Type pulumi.StringPtrInput
}

func (HostSetPluginState) ElementType() reflect.Type {
	return reflect.TypeOf((*hostSetPluginState)(nil)).Elem()
}

type hostSetPluginArgs struct {
	// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
	// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
	AttributesJson *string `pulumi:"attributesJson"`
	// The host set description.
	Description *string `pulumi:"description"`
	// The catalog for the host set.
	HostCatalogId string `pulumi:"hostCatalogId"`
	// The host set name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The ordered list of preferred endpoints.
	PreferredEndpoints []string `pulumi:"preferredEndpoints"`
	// The value to set for the sync interval seconds.
	SyncIntervalSeconds *int `pulumi:"syncIntervalSeconds"`
	// The type of host set
	Type *string `pulumi:"type"`
}

// The set of arguments for constructing a HostSetPlugin resource.
type HostSetPluginArgs struct {
	// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
	// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
	AttributesJson pulumi.StringPtrInput
	// The host set description.
	Description pulumi.StringPtrInput
	// The catalog for the host set.
	HostCatalogId pulumi.StringInput
	// The host set name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The ordered list of preferred endpoints.
	PreferredEndpoints pulumi.StringArrayInput
	// The value to set for the sync interval seconds.
	SyncIntervalSeconds pulumi.IntPtrInput
	// The type of host set
	Type pulumi.StringPtrInput
}

func (HostSetPluginArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hostSetPluginArgs)(nil)).Elem()
}

type HostSetPluginInput interface {
	pulumi.Input

	ToHostSetPluginOutput() HostSetPluginOutput
	ToHostSetPluginOutputWithContext(ctx context.Context) HostSetPluginOutput
}

func (*HostSetPlugin) ElementType() reflect.Type {
	return reflect.TypeOf((**HostSetPlugin)(nil)).Elem()
}

func (i *HostSetPlugin) ToHostSetPluginOutput() HostSetPluginOutput {
	return i.ToHostSetPluginOutputWithContext(context.Background())
}

func (i *HostSetPlugin) ToHostSetPluginOutputWithContext(ctx context.Context) HostSetPluginOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetPluginOutput)
}

// HostSetPluginArrayInput is an input type that accepts HostSetPluginArray and HostSetPluginArrayOutput values.
// You can construct a concrete instance of `HostSetPluginArrayInput` via:
//
//          HostSetPluginArray{ HostSetPluginArgs{...} }
type HostSetPluginArrayInput interface {
	pulumi.Input

	ToHostSetPluginArrayOutput() HostSetPluginArrayOutput
	ToHostSetPluginArrayOutputWithContext(context.Context) HostSetPluginArrayOutput
}

type HostSetPluginArray []HostSetPluginInput

func (HostSetPluginArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HostSetPlugin)(nil)).Elem()
}

func (i HostSetPluginArray) ToHostSetPluginArrayOutput() HostSetPluginArrayOutput {
	return i.ToHostSetPluginArrayOutputWithContext(context.Background())
}

func (i HostSetPluginArray) ToHostSetPluginArrayOutputWithContext(ctx context.Context) HostSetPluginArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetPluginArrayOutput)
}

// HostSetPluginMapInput is an input type that accepts HostSetPluginMap and HostSetPluginMapOutput values.
// You can construct a concrete instance of `HostSetPluginMapInput` via:
//
//          HostSetPluginMap{ "key": HostSetPluginArgs{...} }
type HostSetPluginMapInput interface {
	pulumi.Input

	ToHostSetPluginMapOutput() HostSetPluginMapOutput
	ToHostSetPluginMapOutputWithContext(context.Context) HostSetPluginMapOutput
}

type HostSetPluginMap map[string]HostSetPluginInput

func (HostSetPluginMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HostSetPlugin)(nil)).Elem()
}

func (i HostSetPluginMap) ToHostSetPluginMapOutput() HostSetPluginMapOutput {
	return i.ToHostSetPluginMapOutputWithContext(context.Background())
}

func (i HostSetPluginMap) ToHostSetPluginMapOutputWithContext(ctx context.Context) HostSetPluginMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HostSetPluginMapOutput)
}

type HostSetPluginOutput struct{ *pulumi.OutputState }

func (HostSetPluginOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HostSetPlugin)(nil)).Elem()
}

func (o HostSetPluginOutput) ToHostSetPluginOutput() HostSetPluginOutput {
	return o
}

func (o HostSetPluginOutput) ToHostSetPluginOutputWithContext(ctx context.Context) HostSetPluginOutput {
	return o
}

// The attributes for the host set. Either values encoded with the "jsonencode" function, pre-escaped JSON string, or a
// file:// or env:// path. Set to a string "null" or remove the block to clear all attributes in the host set.
func (o HostSetPluginOutput) AttributesJson() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringPtrOutput { return v.AttributesJson }).(pulumi.StringPtrOutput)
}

// The host set description.
func (o HostSetPluginOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The catalog for the host set.
func (o HostSetPluginOutput) HostCatalogId() pulumi.StringOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringOutput { return v.HostCatalogId }).(pulumi.StringOutput)
}

// The host set name. Defaults to the resource name.
func (o HostSetPluginOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The ordered list of preferred endpoints.
func (o HostSetPluginOutput) PreferredEndpoints() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringArrayOutput { return v.PreferredEndpoints }).(pulumi.StringArrayOutput)
}

// The value to set for the sync interval seconds.
func (o HostSetPluginOutput) SyncIntervalSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.IntPtrOutput { return v.SyncIntervalSeconds }).(pulumi.IntPtrOutput)
}

// The type of host set
func (o HostSetPluginOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HostSetPlugin) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type HostSetPluginArrayOutput struct{ *pulumi.OutputState }

func (HostSetPluginArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HostSetPlugin)(nil)).Elem()
}

func (o HostSetPluginArrayOutput) ToHostSetPluginArrayOutput() HostSetPluginArrayOutput {
	return o
}

func (o HostSetPluginArrayOutput) ToHostSetPluginArrayOutputWithContext(ctx context.Context) HostSetPluginArrayOutput {
	return o
}

func (o HostSetPluginArrayOutput) Index(i pulumi.IntInput) HostSetPluginOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HostSetPlugin {
		return vs[0].([]*HostSetPlugin)[vs[1].(int)]
	}).(HostSetPluginOutput)
}

type HostSetPluginMapOutput struct{ *pulumi.OutputState }

func (HostSetPluginMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HostSetPlugin)(nil)).Elem()
}

func (o HostSetPluginMapOutput) ToHostSetPluginMapOutput() HostSetPluginMapOutput {
	return o
}

func (o HostSetPluginMapOutput) ToHostSetPluginMapOutputWithContext(ctx context.Context) HostSetPluginMapOutput {
	return o
}

func (o HostSetPluginMapOutput) MapIndex(k pulumi.StringInput) HostSetPluginOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HostSetPlugin {
		return vs[0].(map[string]*HostSetPlugin)[vs[1].(string)]
	}).(HostSetPluginOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetPluginInput)(nil)).Elem(), &HostSetPlugin{})
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetPluginArrayInput)(nil)).Elem(), HostSetPluginArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HostSetPluginMapInput)(nil)).Elem(), HostSetPluginMap{})
	pulumi.RegisterOutputType(HostSetPluginOutput{})
	pulumi.RegisterOutputType(HostSetPluginArrayOutput{})
	pulumi.RegisterOutputType(HostSetPluginMapOutput{})
}
