// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Role struct {
	pulumi.CustomResourceState

	// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
	// specialized behavior to allow it to be imported and managed.
	DefaultRole pulumi.BoolPtrOutput `pulumi:"defaultRole"`
	// The role description.
	Description  pulumi.StringPtrOutput `pulumi:"description"`
	GrantScopeId pulumi.StringOutput    `pulumi:"grantScopeId"`
	// A list of stringified grants for the role.
	GrantStrings pulumi.StringArrayOutput `pulumi:"grantStrings"`
	// The role name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// A list of principal (user or group) IDs to add as principals on the role.
	PrincipalIds pulumi.StringArrayOutput `pulumi:"principalIds"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId pulumi.StringOutput `pulumi:"scopeId"`
}

// NewRole registers a new resource with the given unique name, arguments, and options.
func NewRole(ctx *pulumi.Context,
	name string, args *RoleArgs, opts ...pulumi.ResourceOption) (*Role, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ScopeId == nil {
		return nil, errors.New("invalid value for required argument 'ScopeId'")
	}
	var resource Role
	err := ctx.RegisterResource("boundary:index/role:Role", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRole gets an existing Role resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RoleState, opts ...pulumi.ResourceOption) (*Role, error) {
	var resource Role
	err := ctx.ReadResource("boundary:index/role:Role", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Role resources.
type roleState struct {
	// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
	// specialized behavior to allow it to be imported and managed.
	DefaultRole *bool `pulumi:"defaultRole"`
	// The role description.
	Description  *string `pulumi:"description"`
	GrantScopeId *string `pulumi:"grantScopeId"`
	// A list of stringified grants for the role.
	GrantStrings []string `pulumi:"grantStrings"`
	// The role name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// A list of principal (user or group) IDs to add as principals on the role.
	PrincipalIds []string `pulumi:"principalIds"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId *string `pulumi:"scopeId"`
}

type RoleState struct {
	// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
	// specialized behavior to allow it to be imported and managed.
	DefaultRole pulumi.BoolPtrInput
	// The role description.
	Description  pulumi.StringPtrInput
	GrantScopeId pulumi.StringPtrInput
	// A list of stringified grants for the role.
	GrantStrings pulumi.StringArrayInput
	// The role name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// A list of principal (user or group) IDs to add as principals on the role.
	PrincipalIds pulumi.StringArrayInput
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId pulumi.StringPtrInput
}

func (RoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*roleState)(nil)).Elem()
}

type roleArgs struct {
	// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
	// specialized behavior to allow it to be imported and managed.
	DefaultRole *bool `pulumi:"defaultRole"`
	// The role description.
	Description  *string `pulumi:"description"`
	GrantScopeId *string `pulumi:"grantScopeId"`
	// A list of stringified grants for the role.
	GrantStrings []string `pulumi:"grantStrings"`
	// The role name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// A list of principal (user or group) IDs to add as principals on the role.
	PrincipalIds []string `pulumi:"principalIds"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId string `pulumi:"scopeId"`
}

// The set of arguments for constructing a Role resource.
type RoleArgs struct {
	// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
	// specialized behavior to allow it to be imported and managed.
	DefaultRole pulumi.BoolPtrInput
	// The role description.
	Description  pulumi.StringPtrInput
	GrantScopeId pulumi.StringPtrInput
	// A list of stringified grants for the role.
	GrantStrings pulumi.StringArrayInput
	// The role name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// A list of principal (user or group) IDs to add as principals on the role.
	PrincipalIds pulumi.StringArrayInput
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId pulumi.StringInput
}

func (RoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*roleArgs)(nil)).Elem()
}

type RoleInput interface {
	pulumi.Input

	ToRoleOutput() RoleOutput
	ToRoleOutputWithContext(ctx context.Context) RoleOutput
}

func (*Role) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (i *Role) ToRoleOutput() RoleOutput {
	return i.ToRoleOutputWithContext(context.Background())
}

func (i *Role) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleOutput)
}

// RoleArrayInput is an input type that accepts RoleArray and RoleArrayOutput values.
// You can construct a concrete instance of `RoleArrayInput` via:
//
//          RoleArray{ RoleArgs{...} }
type RoleArrayInput interface {
	pulumi.Input

	ToRoleArrayOutput() RoleArrayOutput
	ToRoleArrayOutputWithContext(context.Context) RoleArrayOutput
}

type RoleArray []RoleInput

func (RoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (i RoleArray) ToRoleArrayOutput() RoleArrayOutput {
	return i.ToRoleArrayOutputWithContext(context.Background())
}

func (i RoleArray) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleArrayOutput)
}

// RoleMapInput is an input type that accepts RoleMap and RoleMapOutput values.
// You can construct a concrete instance of `RoleMapInput` via:
//
//          RoleMap{ "key": RoleArgs{...} }
type RoleMapInput interface {
	pulumi.Input

	ToRoleMapOutput() RoleMapOutput
	ToRoleMapOutputWithContext(context.Context) RoleMapOutput
}

type RoleMap map[string]RoleInput

func (RoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (i RoleMap) ToRoleMapOutput() RoleMapOutput {
	return i.ToRoleMapOutputWithContext(context.Background())
}

func (i RoleMap) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RoleMapOutput)
}

type RoleOutput struct{ *pulumi.OutputState }

func (RoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Role)(nil)).Elem()
}

func (o RoleOutput) ToRoleOutput() RoleOutput {
	return o
}

func (o RoleOutput) ToRoleOutputWithContext(ctx context.Context) RoleOutput {
	return o
}

// Indicates that the role containing this value is the default role (that is, has the id 'r_default'), which triggers some
// specialized behavior to allow it to be imported and managed.
func (o RoleOutput) DefaultRole() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.BoolPtrOutput { return v.DefaultRole }).(pulumi.BoolPtrOutput)
}

// The role description.
func (o RoleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Role) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o RoleOutput) GrantScopeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.GrantScopeId }).(pulumi.StringOutput)
}

// A list of stringified grants for the role.
func (o RoleOutput) GrantStrings() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Role) pulumi.StringArrayOutput { return v.GrantStrings }).(pulumi.StringArrayOutput)
}

// The role name. Defaults to the resource name.
func (o RoleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A list of principal (user or group) IDs to add as principals on the role.
func (o RoleOutput) PrincipalIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Role) pulumi.StringArrayOutput { return v.PrincipalIds }).(pulumi.StringArrayOutput)
}

// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
func (o RoleOutput) ScopeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Role) pulumi.StringOutput { return v.ScopeId }).(pulumi.StringOutput)
}

type RoleArrayOutput struct{ *pulumi.OutputState }

func (RoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Role)(nil)).Elem()
}

func (o RoleArrayOutput) ToRoleArrayOutput() RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) ToRoleArrayOutputWithContext(ctx context.Context) RoleArrayOutput {
	return o
}

func (o RoleArrayOutput) Index(i pulumi.IntInput) RoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Role {
		return vs[0].([]*Role)[vs[1].(int)]
	}).(RoleOutput)
}

type RoleMapOutput struct{ *pulumi.OutputState }

func (RoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Role)(nil)).Elem()
}

func (o RoleMapOutput) ToRoleMapOutput() RoleMapOutput {
	return o
}

func (o RoleMapOutput) ToRoleMapOutputWithContext(ctx context.Context) RoleMapOutput {
	return o
}

func (o RoleMapOutput) MapIndex(k pulumi.StringInput) RoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Role {
		return vs[0].(map[string]*Role)[vs[1].(string)]
	}).(RoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RoleInput)(nil)).Elem(), &Role{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleArrayInput)(nil)).Elem(), RoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RoleMapInput)(nil)).Elem(), RoleMap{})
	pulumi.RegisterOutputType(RoleOutput{})
	pulumi.RegisterOutputType(RoleArrayOutput{})
	pulumi.RegisterOutputType(RoleMapOutput{})
}
