// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package boundary

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Target struct {
	pulumi.CustomResourceState

	// A list of application credential source ID's.
	ApplicationCredentialSourceIds pulumi.StringArrayOutput `pulumi:"applicationCredentialSourceIds"`
	// The default port for this target.
	DefaultPort pulumi.IntPtrOutput `pulumi:"defaultPort"`
	// The target description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// A list of host source ID's.
	HostSourceIds pulumi.StringArrayOutput `pulumi:"hostSourceIds"`
	// The target name. Defaults to the resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId                pulumi.StringOutput `pulumi:"scopeId"`
	SessionConnectionLimit pulumi.IntOutput    `pulumi:"sessionConnectionLimit"`
	SessionMaxSeconds      pulumi.IntOutput    `pulumi:"sessionMaxSeconds"`
	// The target resource type.
	Type pulumi.StringOutput `pulumi:"type"`
	// Boolean expression to filter the workers for this target
	WorkerFilter pulumi.StringPtrOutput `pulumi:"workerFilter"`
}

// NewTarget registers a new resource with the given unique name, arguments, and options.
func NewTarget(ctx *pulumi.Context,
	name string, args *TargetArgs, opts ...pulumi.ResourceOption) (*Target, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ScopeId == nil {
		return nil, errors.New("invalid value for required argument 'ScopeId'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	var resource Target
	err := ctx.RegisterResource("boundary:index/target:Target", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTarget gets an existing Target resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTarget(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TargetState, opts ...pulumi.ResourceOption) (*Target, error) {
	var resource Target
	err := ctx.ReadResource("boundary:index/target:Target", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Target resources.
type targetState struct {
	// A list of application credential source ID's.
	ApplicationCredentialSourceIds []string `pulumi:"applicationCredentialSourceIds"`
	// The default port for this target.
	DefaultPort *int `pulumi:"defaultPort"`
	// The target description.
	Description *string `pulumi:"description"`
	// A list of host source ID's.
	HostSourceIds []string `pulumi:"hostSourceIds"`
	// The target name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId                *string `pulumi:"scopeId"`
	SessionConnectionLimit *int    `pulumi:"sessionConnectionLimit"`
	SessionMaxSeconds      *int    `pulumi:"sessionMaxSeconds"`
	// The target resource type.
	Type *string `pulumi:"type"`
	// Boolean expression to filter the workers for this target
	WorkerFilter *string `pulumi:"workerFilter"`
}

type TargetState struct {
	// A list of application credential source ID's.
	ApplicationCredentialSourceIds pulumi.StringArrayInput
	// The default port for this target.
	DefaultPort pulumi.IntPtrInput
	// The target description.
	Description pulumi.StringPtrInput
	// A list of host source ID's.
	HostSourceIds pulumi.StringArrayInput
	// The target name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId                pulumi.StringPtrInput
	SessionConnectionLimit pulumi.IntPtrInput
	SessionMaxSeconds      pulumi.IntPtrInput
	// The target resource type.
	Type pulumi.StringPtrInput
	// Boolean expression to filter the workers for this target
	WorkerFilter pulumi.StringPtrInput
}

func (TargetState) ElementType() reflect.Type {
	return reflect.TypeOf((*targetState)(nil)).Elem()
}

type targetArgs struct {
	// A list of application credential source ID's.
	ApplicationCredentialSourceIds []string `pulumi:"applicationCredentialSourceIds"`
	// The default port for this target.
	DefaultPort *int `pulumi:"defaultPort"`
	// The target description.
	Description *string `pulumi:"description"`
	// A list of host source ID's.
	HostSourceIds []string `pulumi:"hostSourceIds"`
	// The target name. Defaults to the resource name.
	Name *string `pulumi:"name"`
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId                string `pulumi:"scopeId"`
	SessionConnectionLimit *int   `pulumi:"sessionConnectionLimit"`
	SessionMaxSeconds      *int   `pulumi:"sessionMaxSeconds"`
	// The target resource type.
	Type string `pulumi:"type"`
	// Boolean expression to filter the workers for this target
	WorkerFilter *string `pulumi:"workerFilter"`
}

// The set of arguments for constructing a Target resource.
type TargetArgs struct {
	// A list of application credential source ID's.
	ApplicationCredentialSourceIds pulumi.StringArrayInput
	// The default port for this target.
	DefaultPort pulumi.IntPtrInput
	// The target description.
	Description pulumi.StringPtrInput
	// A list of host source ID's.
	HostSourceIds pulumi.StringArrayInput
	// The target name. Defaults to the resource name.
	Name pulumi.StringPtrInput
	// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
	ScopeId                pulumi.StringInput
	SessionConnectionLimit pulumi.IntPtrInput
	SessionMaxSeconds      pulumi.IntPtrInput
	// The target resource type.
	Type pulumi.StringInput
	// Boolean expression to filter the workers for this target
	WorkerFilter pulumi.StringPtrInput
}

func (TargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*targetArgs)(nil)).Elem()
}

type TargetInput interface {
	pulumi.Input

	ToTargetOutput() TargetOutput
	ToTargetOutputWithContext(ctx context.Context) TargetOutput
}

func (*Target) ElementType() reflect.Type {
	return reflect.TypeOf((**Target)(nil)).Elem()
}

func (i *Target) ToTargetOutput() TargetOutput {
	return i.ToTargetOutputWithContext(context.Background())
}

func (i *Target) ToTargetOutputWithContext(ctx context.Context) TargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetOutput)
}

// TargetArrayInput is an input type that accepts TargetArray and TargetArrayOutput values.
// You can construct a concrete instance of `TargetArrayInput` via:
//
//          TargetArray{ TargetArgs{...} }
type TargetArrayInput interface {
	pulumi.Input

	ToTargetArrayOutput() TargetArrayOutput
	ToTargetArrayOutputWithContext(context.Context) TargetArrayOutput
}

type TargetArray []TargetInput

func (TargetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Target)(nil)).Elem()
}

func (i TargetArray) ToTargetArrayOutput() TargetArrayOutput {
	return i.ToTargetArrayOutputWithContext(context.Background())
}

func (i TargetArray) ToTargetArrayOutputWithContext(ctx context.Context) TargetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetArrayOutput)
}

// TargetMapInput is an input type that accepts TargetMap and TargetMapOutput values.
// You can construct a concrete instance of `TargetMapInput` via:
//
//          TargetMap{ "key": TargetArgs{...} }
type TargetMapInput interface {
	pulumi.Input

	ToTargetMapOutput() TargetMapOutput
	ToTargetMapOutputWithContext(context.Context) TargetMapOutput
}

type TargetMap map[string]TargetInput

func (TargetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Target)(nil)).Elem()
}

func (i TargetMap) ToTargetMapOutput() TargetMapOutput {
	return i.ToTargetMapOutputWithContext(context.Background())
}

func (i TargetMap) ToTargetMapOutputWithContext(ctx context.Context) TargetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TargetMapOutput)
}

type TargetOutput struct{ *pulumi.OutputState }

func (TargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Target)(nil)).Elem()
}

func (o TargetOutput) ToTargetOutput() TargetOutput {
	return o
}

func (o TargetOutput) ToTargetOutputWithContext(ctx context.Context) TargetOutput {
	return o
}

// A list of application credential source ID's.
func (o TargetOutput) ApplicationCredentialSourceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Target) pulumi.StringArrayOutput { return v.ApplicationCredentialSourceIds }).(pulumi.StringArrayOutput)
}

// The default port for this target.
func (o TargetOutput) DefaultPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Target) pulumi.IntPtrOutput { return v.DefaultPort }).(pulumi.IntPtrOutput)
}

// The target description.
func (o TargetOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Target) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// A list of host source ID's.
func (o TargetOutput) HostSourceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Target) pulumi.StringArrayOutput { return v.HostSourceIds }).(pulumi.StringArrayOutput)
}

// The target name. Defaults to the resource name.
func (o TargetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Target) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The scope ID in which the resource is created. Defaults to the provider's `default_scope` if unset.
func (o TargetOutput) ScopeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Target) pulumi.StringOutput { return v.ScopeId }).(pulumi.StringOutput)
}

func (o TargetOutput) SessionConnectionLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *Target) pulumi.IntOutput { return v.SessionConnectionLimit }).(pulumi.IntOutput)
}

func (o TargetOutput) SessionMaxSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *Target) pulumi.IntOutput { return v.SessionMaxSeconds }).(pulumi.IntOutput)
}

// The target resource type.
func (o TargetOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Target) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Boolean expression to filter the workers for this target
func (o TargetOutput) WorkerFilter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Target) pulumi.StringPtrOutput { return v.WorkerFilter }).(pulumi.StringPtrOutput)
}

type TargetArrayOutput struct{ *pulumi.OutputState }

func (TargetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Target)(nil)).Elem()
}

func (o TargetArrayOutput) ToTargetArrayOutput() TargetArrayOutput {
	return o
}

func (o TargetArrayOutput) ToTargetArrayOutputWithContext(ctx context.Context) TargetArrayOutput {
	return o
}

func (o TargetArrayOutput) Index(i pulumi.IntInput) TargetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Target {
		return vs[0].([]*Target)[vs[1].(int)]
	}).(TargetOutput)
}

type TargetMapOutput struct{ *pulumi.OutputState }

func (TargetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Target)(nil)).Elem()
}

func (o TargetMapOutput) ToTargetMapOutput() TargetMapOutput {
	return o
}

func (o TargetMapOutput) ToTargetMapOutputWithContext(ctx context.Context) TargetMapOutput {
	return o
}

func (o TargetMapOutput) MapIndex(k pulumi.StringInput) TargetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Target {
		return vs[0].(map[string]*Target)[vs[1].(string)]
	}).(TargetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TargetInput)(nil)).Elem(), &Target{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetArrayInput)(nil)).Elem(), TargetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TargetMapInput)(nil)).Elem(), TargetMap{})
	pulumi.RegisterOutputType(TargetOutput{})
	pulumi.RegisterOutputType(TargetArrayOutput{})
	pulumi.RegisterOutputType(TargetMapOutput{})
}
